### ISSUE TITLE
Bug en la validacion de los inputs

### ISSUE THREAD

**Issue by RegemLux** [Ekrilex/Vial-Manager#16]
Tanto el archivo registrar.php y update.php contienen el mismo formulario, por ende en dicho formulario se viene presentando un bug a la hora de realizar la validacion de los inputs el cual consiste en que el texto tan solo se visualiza en el primer input y no aparecen los iconos correspondientes a las validaciones.

**Comment by Ekrilex** [comment]
despues de cambiar el evento o funcion de el archivo global de "change" a "keyup", las validaciones siguen sin responder en los formularios descritos

**Comment by RegemLux** [comment]
Se modificaron las validaciones realizadas con jquery a expresiones regulares, generando una solucion al inconveniente
